### ISSUE TITLE
How to switch FINAL.ckpt to FINAL_REAL/IMAG.ckpt?

### ISSUE THREAD

**Issue by zozyaa** [ShinoharaYuuyoru/NoiseReductionUsingGRU#1]
CreateTestDataset generates FINAL.ckpt
In your GRUmodeltest part, you used FINAL_Real/Imag.ckpt, how to switch FINAL.ckpt to FINAL_REAL/IMAG.ckpt?
Does it generates from the CreateTestDataset or generate it directly from FINAL.ckpt? 

-graphPath = os.getcwd() + "/TF_Checkpoints/FINAL.ckpt"
+graphPath_Real = os.getcwd() + "/TF_Checkpoints/FINAL_Real.ckpt"
+graphPath_Imag = os.getcwd() + "/TF_Checkpoints/FINAL_Imag.ckpt"

Thanks

**Comment by ShinoharaYuuyoru** [comment]
I'm really sorry for my tooooo late reply. :sob: 

This project contains two parts:
  1. LSTM model test part
  2. GRU formal model part

In LSTM model test part, the LSTMTestTraining.py will generate FINAL.ckpt. Then, in ModelTest.py will use this *.ckpt file.
That is, ModelTest.py is for LSTM model testing, not for the GRU model, which is the formal model.
Actually, you may find that ModelTest.py using lstm_cell = tf.contrib.rnn.BasicLSTMCell(...), not gru_cell.

And in GRU formal model part, we will use GRUTraining.py and GRUModelTest.py to train and test the model.
And this will generate and use FINAL_Real/Imag.ckpt.

Again, I'm really sorry for my ignorance and I appreciate your tolerance.

Thank you!

**Comment by Krishankantmani3** [comment]
But GRU model is not generating FINAL_Real.ckpt/FINAL_Imag.ckpt  such kind of file in TF_Checkpoints folder .
here is list of  file created in it :
1.checkpoints
2.FINAL.ckpt.data
3.FINAL.ckpt.index
4.FINAL.ckpt.meta
what should I do to run code ?
help me  as soon as possible plz

**Comment by ShinoharaYuuyoru** [comment]
Thank you for your issue.

I reviewed the code again, then I found that I didn’t explain the processes well.
In fact, this work will train two models, one for Real number part, and another for Imagine number part.
1. Create datasets.
2. Use GRUTrain.py, training real/imagine model SEPARATELY, to get FINAL_Real/Imag.ckpt. You should change the *.ckpt output file name in the code manually.
3. Use GRUTest.py(actually this is an final *.wav files output script using two models) to get your result.

Thank you and may this help you.

**Comment by Krishankantmani3** [comment]
I am thankful for your response. it really helped me a lot but there is a problem in running code as it is taking 20-30 days if epochs=250 and batch_size=10 with 2000 dataset.so my question is 

1) how did you train this model? and how long did it take?
2) is there any solution to minimize time to train or is there any limit of adjustment of epochs and batch size.

please reply to my comment.
Thanking you.

**Comment by ShinoharaYuuyoru** [comment]
Thanks for your questions.
I remember that I trained with my lab's server which had several NVIDIA TITAN X and I used two of them to train my model.
So, actually, the training took not so much time at that time...
And the training parameters in the code is mainly the final configuration of training. Also, the project has been one and half year already, so I have no idea to accelerate training speed further now...
Sorry for this no contribution comment.

**Comment by thisislohith6** [comment]
Hi, I have followed all the steps to run the model as mentioned in the Readme file, but when I am executing the GRUTraining.py file it is not Generating FINAL_Real.ckpt and FINAL_Imag.ckpt file but when executing GRUModelTest.py it requires Real and Imag ckpt files. So how to generate these files. Could you please help me with this issue.  

Here is list of file created when executing GRUTraining.py file :
1.checkpoints
2.FINAL.ckpt.data-00000-of-00001
3.FINAL.ckpt.index
4.FINAL.ckpt.meta

what should I do to generate real and imag file?
