### ISSUE TITLE
WhiteNoise, BrownianNoise and PinkNoise wav file not found

### ISSUE THREAD

**Issue by projectdrone2** [ShinoharaYuuyoru/NoiseReductionUsingGRU#3]
Dear Shinohara Yuuyoru,

Thank you for putting your work on GitHub.
I wasn't able to find the following 3 files. Do you know where I can download them?

Thanks for your help!

whiteNoise = "WhiteNoise.wav"
brownianNoise = "BrownianNoise.wav"
pinkNoise = "PinkNoise.wav"

**Comment by ShinoharaYuuyoru** [comment]
Sorry for my late reply... :(

You can find the three kinds of noise in adityatb's work:
https://github.com/adityatb/noise-reduction-using-rnn/tree/master/Noises

Good luck!
